2020-04-13 22:53:06.083 +01:00 [Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An established connection was aborted by the software in your host machine.
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.Gang.IGangMember.ConnectAsync(Func`2 onReceiveAsync) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 43
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 53
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_1.<<UseWebSocketGangs>b__1>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-04-13 22:53:06.092 +01:00 [Warning] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: The response has already started, the error page middleware will not be executed.
2020-04-13 22:53:06.099 +01:00 [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLUVUHBHMI6J", Request id "0HLUVUHBHMI6J:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An established connection was aborted by the software in your host machine.
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.Gang.IGangMember.ConnectAsync(Func`2 onReceiveAsync) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 43
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 53
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_1.<<UseWebSocketGangs>b__1>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-04-14 17:54:50.973 +01:00 [Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.Gang.IGangMember.ConnectAsync(String gangId, Func`2 onReceiveAsync) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 45
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 53
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_1.<<UseWebSocketGangs>b__1>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-04-14 17:54:50.973 +01:00 [Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.Gang.IGangMember.ConnectAsync(String gangId, Func`2 onReceiveAsync) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 45
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 53
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_1.<<UseWebSocketGangs>b__1>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-04-14 17:54:50.982 +01:00 [Warning] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: The response has already started, the error page middleware will not be executed.
2020-04-14 17:54:50.984 +01:00 [Warning] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: The response has already started, the error page middleware will not be executed.
2020-04-14 17:54:51.142 +01:00 [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV0IFBLBI2M", Request id "0HLV0IFBLBI2M:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.Gang.IGangMember.ConnectAsync(String gangId, Func`2 onReceiveAsync) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 45
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 53
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_1.<<UseWebSocketGangs>b__1>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-04-14 17:54:51.142 +01:00 [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV0IFBLBI2N", Request id "0HLV0IFBLBI2N:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.Gang.IGangMember.ConnectAsync(String gangId, Func`2 onReceiveAsync) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 45
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 53
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_1.<<UseWebSocketGangs>b__1>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-08-24 23:06:11.013 +01:00 [Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.<>c__DisplayClass7_0.<<Gang-IGangMember-ConnectAsync>b__0>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 39
--- End of stack trace from previous location ---
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 95
   at Gang.GangExtensions.BlockAsync(Task`1 task) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangExtensions.cs:line 14
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_0.<<UseWebSocketGangs>b__2>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 65
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-24 23:06:11.026 +01:00 [Warning] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: The response has already started, the error page middleware will not be executed.
2020-08-24 23:06:11.047 +01:00 [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM28F7736F5E", Request id "0HM28F7736F5E:00000002": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Gang.WebSockets.WebSocketGangMember.<>c__DisplayClass7_0.<<Gang-IGangMember-ConnectAsync>b__0>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangMember.cs:line 39
--- End of stack trace from previous location ---
   at Gang.GangHandler.Gang.IGangHandler.HandleAsync(GangParameters parameters, IGangMember gangMember) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangHandler.cs:line 95
   at Gang.GangExtensions.BlockAsync(Task`1 task) in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang\GangExtensions.cs:line 14
   at Gang.WebSockets.WebSocketGangConfiguration.<>c__DisplayClass1_0.<<UseWebSocketGangs>b__2>d.MoveNext() in C:\Users\ant.ANTIX\Source\Repos\gang\src\Gang.WebSockets\WebSocketGangConfiguration.cs:line 65
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequest[TContext](IHttpApplication`1 application)
